### ISSUE TITLE
Feature Request - Home Assistant support

### ISSUE THREAD

**Issue by alheureux88** [titilambert/pyebox#2]
Hello Titilambert, I was about to create an home assistant sensor component for ebox but saw that you were the one that created the hydro quebec one and you already have this python code to look it up. I was wondering if you were already in the process of writing it or not.

If not, as I have 0 experience with python and installed home assistant yesterday, I wanted to either depend on this (if it is even possible) or be "heavily" inspired by it with code thank you/link to your repo if you don't mind.

**Comment by titilambert** [comment]
I already made a Home assistant sensor: https://home-assistant.io/components/sensor.ebox/
